name: generate 3d chart for profile contributions

on:
  schedule:           # daily at 18 UTC
    - cron: '0 18 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # ── checkout ───────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4

      # ── build day.svg / night.svg from your bitmap JSON ────────
      - name: Generate SVGs (day & night)
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:      ${{ github.repository_owner }}
          SETTING_JSON:  conf/github-profile-3d-contrib.json

      # ── splice rainbow CSS into every SVG ───────────────────────
      - name: Inject CSS overrides (desktop + mobile)
        run: |
          tmp=$(mktemp)
          cat >"$tmp"<<'CSS'
          /* ===== rainbow animation (hue-rotate filter) ===== */
          @-webkit-keyframes legoRainbow {
            0%   { -webkit-filter: hue-rotate(0deg);    filter: hue-rotate(0deg); }
            100% { -webkit-filter: hue-rotate(360deg);  filter: hue-rotate(360deg); }
          }
          @keyframes legoRainbow {
            0%   { -webkit-filter: hue-rotate(0deg);    filter: hue-rotate(0deg); }
            100% { -webkit-filter: hue-rotate(360deg);  filter: hue-rotate(360deg); }
          }

          /* Apply rainbow filter animation to active contribution blocks */
          g rect[data-level]:not([data-level="0"]) {
            -webkit-animation: legoRainbow 4s linear infinite;
                    animation: legoRainbow 4s linear infinite;
          }

          /* (Optional) Staggered animation delays for a multi-phase rainbow */
          g rect[data-level]:not([data-level="0"]):nth-of-type(5n+1) { animation-delay: -0.8s; }
          g rect[data-level]:not([data-level="0"]):nth-of-type(5n+2) { animation-delay: -1.6s; }
          g rect[data-level]:not([data-level="0"]):nth-of-type(5n+3) { animation-delay: -2.4s; }
          g rect[data-level]:not([data-level="0"]):nth-of-type(5n+4) { animation-delay: -3.2s; }
          /* Note: The above nth-of-type selectors distribute 5 different start phases.
             They are optional; remove them if you prefer the unison animation. */

          /* extras (unchanged) */
          .stroke-fg { stroke: #0000ff; }
          .radar    { stroke-width:4px; fill:#0dff00; fill-opacity:.5; stroke:#ff0000; }
          CSS

          # Insert the CSS block right after the first <style> tag in each SVG
          for svg in profile-3d-contrib/*.svg; do
            sed -i '/<style>/r '"$tmp" "$svg"
          done

      # ── publish finished SVGs ──────────────────────────────────
      - name: Push SVGs to output-3d-contrib branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
