# .github/workflows/profile-3d.yml
name: GitHub‑Profile‑3D‑Contrib

on:
  schedule:
    - cron: "0 18 * * *"          # daily at 18 UTC
  workflow_dispatch:              # manual “Run workflow”

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1 Check out repo
      - uses: actions/checkout@v4

      # 2 Generate SVG from JSON
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:      ${{ github.repository_owner }}
          SETTING_JSON:  conf/github-profile-3d-contrib.json

      # 3 Append your custom CSS so it overrides everything else
      - name: Append custom style
        run: |
          svg="profile-3d-contrib/profile-night-rainbow.svg"
          css=$(cat conf/custom-style.css)
          # place our style right before </svg>
          perl -0777 -i -pe "s|</svg>|<style>\n${css//$'\n'/\\n}\n</style>\n</svg>|" "$svg"

      # 4 Keep only the customised SVG
      - name: Remove any other SVGs
        run: |
          cd profile-3d-contrib
          for f in *; do
            [ "$f" = "profile-night-rainbow.svg" ] || rm -f "$f"
          done
          cd ..

      # 5 Commit if the file changed
      - name: Commit & Push
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update of custom night‑rainbow SVG"
            git push
          fi
