name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron:  "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run 3D-Contrib generator
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:      ${{ github.repository_owner }}
          SETTING_JSON:  .github/profile-3d-settings/night-rainbow.json

      - name: Delete any SVG except the one we want
        run: |
          find profile-3d-contrib -type f -name '*.svg' ! -name 'profile-night-rainbow.svg' -delete

      - name: Commit & push result
        run: |
          git config user.name  "github-actions"
          git config user.email "github-actions@github.com"
          git add -A .
          if git commit -m "Update 3D contribution graph"; then
            git push
          fi
