name: generate 3d chart for profile contributions

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate SVGs (day & night)
        uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME:      ${{ github.repository_owner }}
          SETTING_JSON:  conf/github-profile-3d-contrib.json

      - name: Inject CSS for radar, outline and rainbow hue-rotate
        run: |
          for svg in profile-3d-contrib/*.svg; do
            sed -i '0,/<style>/a\
            @keyframes legoRainbow{0%{filter:hue-rotate(0deg);}100%{filter:hue-rotate(360deg);} }\
            g rect{animation:legoRainbow 4s linear infinite;}\
            .stroke-fg{stroke:#0000ff;}\
            .radar{stroke-width:4px;fill:#0dff00;fill-opacity:0.5;stroke:#ff0000;}\
            ' "$svg"
          done

      - name: Push SVGs to output-3d-contrib branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
